algoritmo "base e expoente"
// Função :
// Autor : Nicoly Holanda
// Data : 15/09/2020

var
cont, base, expo , resu: inteiro

inicio

      escreval( "Digite a base: ")
      leia (base)
      escreval("Digite o expoente: ")
      leia (expo)
      resu<- 1

               para cont de expo ate expo faca
               resu<- base*expo
               fimpara
               escreval(base," elevado a ",expo," é igual a",resu)

fimalgoritmo
