algoritmo "Programa Soma"
//Descrição :
// Autor :  Nicoly Holanda
// Data Atual : 06/09/2020
var
num, soma: inteiro

inicio
soma<-0
num<-1

 
enquanto (num <> 0) faca
          escreval("Digite um numero:")
          leia(num)
          soma <- soma + num
fimenquanto
 
       escreval("*****************")
       escreval("O resultado da soma dos numeros digitados é: ", soma)
            
fimalgoritmo
